"""empty message

Revision ID: 130c0eb8ad9a
Revises: 2c3750025fea
Create Date: 2026-08-23 13:08:57.553873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '130c0eb8ad9a'
down_revision: Union[str, Sequence[str], None] = '2c3750025fea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('seller_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('products_saller_id_fkey'), 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'users', ['seller_id'], ['id'], ondelete='CASCADE')
    op.drop_column('products', 'saller_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('saller_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key(op.f('products_saller_id_fkey'), 'products', 'users', ['saller_id'], ['id'])
    op.drop_column('products', 'seller_id')
    # ### end Alembic commands ###
