"""empty message

Revision ID: 4c2548ef2e0f
Revises: 83721ee6c3b6
Create Date: 2026-09-06 14:56:53.576264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c2548ef2e0f'
down_revision: Union[str, Sequence[str], None] = '83721ee6c3b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_category_name_parent', 'categoryes', ['name', 'parent_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_category_name_parent', 'categoryes', type_='unique')
    # ### end Alembic commands ###
