"""empty message

Revision ID: ab58ac361d4b
Revises: f52c862e54c7
Create Date: 2026-08-25 20:28:06.216665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab58ac361d4b'
down_revision: Union[str, Sequence[str], None] = 'f52c862e54c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart_items', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
