"""empty message

Revision ID: c49a5ad11210
Revises: 130c0eb8ad9a
Create Date: 2026-08-23 20:21:19.823968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c49a5ad11210'
down_revision: Union[str, Sequence[str], None] = '130c0eb8ad9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('products_seller_id_fkey'), 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'users', ['seller_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key(op.f('products_seller_id_fkey'), 'products', 'users', ['seller_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
